### ISSUE TITLE
Оптимизировать хранение логов - вместо Add/Remove сделать циклический список

### ISSUE THREAD

**Issue by justdmitry** [iflight/Logging.Memory#2]
Сейчас при добавлении записи лога выполняется `Remove` и `Add`, при этом `Remove` удаляет элементы из начала списка, [оценка сложности](https://msdn.microsoft.com/ru-ru/library/y33yd2b5%28v=vs.110%29.aspx) `O(n)`.

Можно было бы не трогать размер списка, а зафиксировать его и иметь отдельный `int logListStartIndex`, который бы показывал на "текущий" первый элемент. При достижении конца списка он бы сбрасывался в 0, и дальше старые записи просто бы перезаписывались новыми (сложность сеттера `Item[int32]` [равна](https://msdn.microsoft.com/ru-ru/library/0ebtbkkc%28v=vs.110%29.aspx) `O(1)`)

Тогда надо еще сделать две вещи:
- Отдавая данные наружу (геттер LogList) копировать их в новый List из частей - не проблема, эта операция в разы реже чем добавление новых логов, плюс будет отдаваться копия списка, что предотвратит риск что наш внутрений список будет изменен "получающей" стороной
- Убрать `MaxCount {get; set; }` из каждого логгера, так как они работают с единым списком и логично что должны иметь единое знание о его длине, и они не могут менять это знание "по отдельности".

**Comment by iflight** [comment]
Добавлено в коммите 1adb536
